baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Yuanhao Guo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 1
        - name: News
          url: news/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Publications
          url: publications/
          weight: 4
        - name: Patents
          url: patents/
          weight: 5

params:
    description: "Dr. Yuanhao Guo"
    author: Yuanhao Guo
    DateFormat: "December 2024"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","news","projects","publications","patents"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Yuanhao Guo (郭远昊 博士)
          subtitle: "As a leading expert in artificial intelligence for interdisciplinary applications, I currently serve as the Head of the Intelligent Detection Team and Chief AI Scientist at RoadMaint Co. Ltd., an innovative enterprise affiliated with the Research Institute of Highway, Ministry of Transport (RIOH). Recognized for my technical contributions, I have been appointed as a "Youth Chief Expert" at RIOH, where I drive strategic initiatives in AI-powered road maintenance solutions.\nIn academia, I hold multiple supervisory roles as a Master's Thesis Advisor at Dalian University of Technology, Tianjin University of Technology, and Beijing Jiaotong University, mentoring the next generation of engineers in intelligent transportation systems. Internationally, I contribute to doctoral education as a Committee Member for PhD candidates at the Leiden Institute of Advanced Computer Science, Leiden University.\nMy research program focuses on pioneering the development and practical implementation of cutting-edge artificial intelligence methodologies, particularly deep learning and computer vision architectures, to address complex interdisciplinary challenges. My current research portfolio spans three critical domains: (1) advanced biomedical image processing for drug screening and diseases diagnosis, (2) intelligent road condition assessment and maintenance systems, and (3) perception and decision-making frameworks for autonomous driving technologies. Through these efforts, I bridge the gap between theoretical AI advancements and real-world engineering solutions in transportation infrastructure and beyond.
"
          imageUrl: "yuanhao.jpg"
          imageWidth: 160
          imageHeight: 240
          buttons:
            - name: About
              url: about/
            - name: News
              url: news/
            - name: Projects
              url: projects/
            - name: Publications
              url: publications/
            - name: Patents
              url: patents/

    socialIcons:
        - name: Email
          url: yuanhaoguo@hotmail.com
        - name: Google Scholar
          url: https://scholar.google.nl/citations?user=UlLyPiUAAAAJ&hl=en
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Yuanhao-Guo
        - name: leiden
          url: https://liacs.leidenuniv.nl/~guoy3/


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yuanhao Guo (郭远昊)"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2